### ISSUE TITLE
Repo Cleanup

### ISSUE THREAD

**Issue by drempost** [GuskovAlexey/homework#6]
файлы можно удалять:
[.array1.sh.swp](https://github.com/GuskovAlexey/homework/blob/main/bash/.array1.sh.swp)
[array1.sh](https://github.com/GuskovAlexey/homework/blob/main/bash/array1.sh)
[test.txt](https://github.com/GuskovAlexey/homework/blob/main/bash/test.txt)
[array2.sh](https://github.com/GuskovAlexey/homework/blob/main/bash/array2.sh)
[Currency.sh](https://github.com/GuskovAlexey/homework/blob/main/bash/Lesson12/Currency.sh)

**Comment by GuskovAlexey** [comment]
done
